Repository aidotse/LeakPro, pull requests merged in 2024-08, with the labels that each got.

#101 GPJ: anomalies (isolation forest) analysis and small enhacement to singling out
  leakpro/synthetic_data_attacks/anomalies.py
  leakpro/synthetic_data_attacks/anonymeter/evaluators/singling_out_evaluator.py
  leakpro/synthetic_data_attacks/examples/anomalies_example.ipynb
  leakpro/tests/tests_synthetic_data_attacks/anonymeter_tests/test_singling_out_evaluator.py
  leakpro/tests/tests_synthetic_data_attacks/test_anomalies.py
Labels: enhancement

#108 model handler unit tests
  leakpro/attacks/utils/model_handler.py
  leakpro/tests/model_handlers/test_model_handler.py
  pyproject.toml
Labels: bug, enhancement

#118 removed cache
  .github/workflows/run_tests.yml
Labels: bug

#119 clean cache before test
  .github/workflows/run_tests.yml
Labels: bug

#116 Single softmax
  config/audit.yaml
  config/dev_config/cifar10.yaml
  leakpro/attacks/mia_attacks/rmia.py
  leakpro/attacks/utils/boosting.py
  leakpro/attacks/utils/utils.py
  leakpro/tests/mia_attacks/utils/test_model_handler.py
  leakpro/tests/mia_attacks/utils/test_shadow_model_handler.py
Labels: bug, enhancement

#100 Fl initial
  .gitignore
  config/audit.yaml
  leakpro/attacks/attack_scheduler.py
  leakpro/attacks/gia_attacks/abstract_gia.py
  leakpro/attacks/gia_attacks/attack_factory_gia.py
  leakpro/attacks/gia_attacks/invertinggradients.py
  leakpro/attacks/utils/util_functions.py
  leakpro/dev_utils/data_modules.py
  leakpro/dev_utils/graph_utils.py
  leakpro/fl_utils/gia_module_to_functional.py
  leakpro/fl_utils/gia_optimizers.py
  leakpro/metrics/attack_result.py
  leakpro/shadow_model_blueprints.py
  leakpro/synthetic_data_attacks/examples/inference_example.ipynb
  leakpro/synthetic_data_attacks/examples/singling_out_example.ipynb
  leakpro/tests/conftest.py
  leakpro/user_inputs/abstract_gia_input_handler.py
  leakpro/user_inputs/cifar10_gia_input_handler.py
  leakprofl.py
Labels: enhancement
