Repository aidotse/LeakPro, pull requests merged in 2024-07, with the labels that each got.

#84 GPJ: singling out utils, example and plots
  leakpro/synthetic_data_attacks/examples/inference_example.ipynb
  leakpro/synthetic_data_attacks/examples/singling_out_example.ipynb
  leakpro/synthetic_data_attacks/inference_utils.py
  leakpro/synthetic_data_attacks/plots.py
  leakpro/synthetic_data_attacks/results/res_inference_worst_case_adults.json
  leakpro/synthetic_data_attacks/results/res_singling_out_n_cols_1_adults.json
  leakpro/synthetic_data_attacks/results/res_singling_out_n_cols_all_adults.json
  leakpro/synthetic_data_attacks/singling_out_utils.py
  leakpro/tests/tests_synthetic_data_attacks/test_singling_out_utils.py
Labels: enhancement

#94 Pr86
  config/audit.yaml
  config/dev_config/cifar10.yaml
  leakpro.py
  leakpro/attacks/mia_attacks/abstract_mia.py
  leakpro/attacks/mia_attacks/attack_p.py
  leakpro/attacks/mia_attacks/lira.py
  leakpro/attacks/mia_attacks/loss_trajectory.py
  leakpro/attacks/mia_attacks/qmia.py
  leakpro/attacks/mia_attacks/rmia.py
  leakpro/signals/signal.py
  leakpro/user_inputs/abstract_input_handler.py
Labels: bug, enhancement

#99 unit test for cifar10handler and abstract handler
  leakpro/tests/conftest.py
  leakpro/tests/input_handler/image_utils.py
  leakpro/tests/input_handler/test_image_handler.py
  leakpro/user_inputs/abstract_input_handler.py
Labels: documentation, enhancement
