Repository aidotse/LeakPro, pull requests merged in 2025-02, with the labels that each got.

#208 Optuna
  examples/gia/huang_optuna/main.py
  examples/gia/inverting_celebA_1_image/main.py
  leakpro/attacks/attack_base.py
  leakpro/attacks/gia_attacks/abstract_gia.py
  leakpro/attacks/gia_attacks/huang.py
  leakpro/attacks/gia_attacks/invertinggradients.py
  leakpro/fl_utils/data_utils.py
  leakpro/fl_utils/model_utils.py
  leakpro/fl_utils/similarity_measurements.py
  leakpro/hyperparameter_tuning/optuna.py
  leakpro/run.py
  pyproject.toml
Labels: enhancement

#191 ReadMe Workover
  .github/workflows/run_tests.yml
  README.md
  env_fl.yml
  leakpro/requirements.txt
  pyproject.toml
  resources/.gitkeep
  resources/NER.png
  resources/graph.png
  resources/logo.jpg
  resources/logo.png
  resources/los.png
  resources/mia_flow.png
  resources/surveillance.png
Labels: documentation, enhancement

#197 GPJ: first commit syn_text_pii_scanner with pipeline elements and tests
  examples/synthetic_data/aux/tab_data_aux.py
  examples/synthetic_data/syn_text_pii_scanner_example.ipynb
  leakpro/requirements.txt
  leakpro/synthetic_data_attacks/syn_text_pii_scanner/data_handling.py
  leakpro/synthetic_data_attacks/syn_text_pii_scanner/pii_token_classif_models/ner_longformer_model.py
  leakpro/synthetic_data_attacks/syn_text_pii_scanner/sentence_transformers_models/model.py
  leakpro/synthetic_data_attacks/syn_text_pii_scanner/utils.py
  leakpro/tests/tests_synthetic_data_attacks/tests_syn_text_pii_scanner/data_tests/aux_data_test_CollatorWPadding.py
  leakpro/tests/tests_synthetic_data_attacks/tests_syn_text_pii_scanner/data_tests/aux_data_test_utils.py
  leakpro/tests/tests_synthetic_data_attacks/tests_syn_text_pii_scanner/data_tests/text_data.json
  leakpro/tests/tests_synthetic_data_attacks/tests_syn_text_pii_scanner/data_tests/text_syn_data.json
  leakpro/tests/tests_synthetic_data_attacks/tests_syn_text_pii_scanner/test_data_handling.py
  leakpro/tests/tests_synthetic_data_attacks/tests_syn_text_pii_scanner/test_utils.py
  leakpro/tests/tests_synthetic_data_attacks/tests_syn_text_pii_scanner/tests_pii_token_classif_models/test_ner_longformer_model.py
  pyproject.toml
  third_party.txt
Labels: enhancement

#214 LOS smoother learning
  examples/mia/LOS/audit.yaml
  examples/mia/LOS/mimic_GRUD_handler.py
  examples/mia/LOS/mimic_GRUD_main.ipynb
  examples/mia/LOS/mimic_LR_handler.py
  examples/mia/LOS/mimic_LR_main.ipynb
  examples/mia/LOS/mimiciii_prepration/MIMIC_Extract/datapackage_io_util.py
  examples/mia/LOS/mimiciii_prepration/MIMIC_Extract/heuristic_sentence_splitter.py
  examples/mia/LOS/mimiciii_prepration/MIMIC_Extract/mimic_direct_extract.py
  examples/mia/LOS/mimiciii_prepration/MIMIC_Extract/mimic_querier.py
  examples/mia/LOS/mimiciii_prepration/MIMIC_Extract/utils/simple_impute.py
  examples/mia/LOS/utils/data_processing.py
  examples/mia/LOS/utils/model_GRUD.py
  examples/mia/LOS/utils/model_LR.py
  leakpro/input_handler/handler_setup.py
Labels: bug

#220 Schemas + Handler
  examples/mia/LOS/audit.yaml
  examples/mia/LOS/mimic_GRUD_handler.py
  examples/mia/LOS/mimic_GRUD_main.ipynb
  examples/mia/LOS/mimic_LR_handler.py
  examples/mia/LOS/mimic_LR_main.ipynb
  examples/mia/LOS/utils/model_GRUD.py
  examples/mia/LOS/utils/model_LR.py
  examples/mia/celebA_HQ/audit.yaml
  examples/mia/celebA_HQ/celebA_HQ_handler.py
  examples/mia/celebA_HQ/main_celebA_hq.ipynb
  examples/mia/celebA_HQ/train_config.yaml
  examples/mia/celebA_HQ/utils/celeb_hq_model.py
  examples/mia/cifar/audit.yaml
  examples/mia/cifar/cifar_handler.py
  examples/mia/cifar/cifar_main.ipynb
  examples/mia/cifar/train_config.yaml
  examples/mia/cifar/utils/cifar_model_preparation.py
  examples/mia/tabular_mia/adult_handler.py
  examples/mia/tabular_mia/audit.yaml
  examples/mia/tabular_mia/main.ipynb
  examples/mia/tabular_mia/utils/adult_model_preparation.py
  leakpro/attacks/attack_scheduler.py
  leakpro/attacks/mia_attacks/HSJ.py
  leakpro/attacks/mia_attacks/abstract_mia.py
  leakpro/attacks/mia_attacks/attack_factory_mia.py
  leakpro/attacks/mia_attacks/attack_p.py
  leakpro/attacks/mia_attacks/lira.py
  leakpro/attacks/mia_attacks/loss_trajectory.py
  leakpro/attacks/mia_attacks/qmia.py
  leakpro/attacks/mia_attacks/rmia.py
  leakpro/attacks/mia_attacks/yoqo.py
  leakpro/attacks/utils/distillation_model_handler.py
  leakpro/attacks/utils/model_handler.py
  leakpro/attacks/utils/shadow_model_handler.py
  leakpro/input_handler/abstract_input_handler.py
  leakpro/input_handler/handler_setup.py
  leakpro/input_handler/mia_handler.py
  leakpro/input_handler/modality_extensions/image_extension.py
  leakpro/input_handler/modality_extensions/modality_extension.py
  leakpro/input_handler/modality_extensions/tabular_extension.py
  leakpro/leakpro.py
  leakpro/metrics/attack_result.py
  leakpro/reporting/report_handler.py
  leakpro/requirements.txt
  leakpro/schemas.py
  leakpro/tests/conftest.py
  leakpro/tests/input_handler/image_input_handler.py
  leakpro/tests/input_handler/image_utils.py
  leakpro/tests/input_handler/tabular_input_handler.py
  leakpro/tests/input_handler/tabular_utils.py
  leakpro/tests/input_handler/test_image_handler.py
  leakpro/tests/input_handler/test_tabular_handler.py
  leakpro/tests/mia_attacks/attacks/test_lira.py
  leakpro/tests/mia_attacks/utils/test_model_handler.py
  leakpro/tests/mia_attacks/utils/test_shadow_model_handler.py
  pyproject.toml
Labels: documentation, enhancement

#237 Shadow test accuracy
  examples/mia/tabular_mia/adult_handler.py
  examples/mia/tabular_mia/audit.yaml
  examples/mia/tabular_mia/main.ipynb
  examples/mia/tabular_mia/utils/adult_model_preparation.py
  leakpro/attacks/mia_attacks/lira.py
  leakpro/attacks/utils/shadow_model_handler.py
  leakpro/schemas.py
Labels: documentation, enhancement

#236 Rmia unit test
  leakpro/tests/constants.py
  leakpro/tests/mia_attacks/attacks/test_lira.py
  leakpro/tests/mia_attacks/attacks/test_rmia.py
Labels: documentation, enhancement

#238 Audit all data
  examples/mia/cifar/audit.yaml
  leakpro/attacks/mia_attacks/HSJ.py
  leakpro/attacks/mia_attacks/abstract_mia.py
  leakpro/attacks/mia_attacks/attack_p.py
  leakpro/attacks/mia_attacks/lira.py
  leakpro/attacks/mia_attacks/loss_trajectory.py
  leakpro/attacks/mia_attacks/qmia.py
  leakpro/attacks/mia_attacks/rmia.py
  leakpro/attacks/mia_attacks/yoqo.py
Labels: bug
