Repository aidotse/LeakPro, pull requests merged in 2025-03, with the labels that each got.

#253 Add personal token to workflow
  .github/workflows/run_tests.yml
Labels: bug

#255 Update run_tests.yml
  .github/workflows/run_tests.yml
Labels: bug

#232 Added Model Inversion Attacks Framework
  examples/minv/celebA/audit.yaml
  examples/minv/celebA/celebA_plgmi_handler.py
  examples/minv/celebA/main_celebA_minv.ipynb
  examples/minv/celebA/train_config.yaml
  examples/minv/celebA/utils/celebA_data.py
  examples/minv/celebA/utils/discriminator.py
  examples/minv/celebA/utils/generator.py
  leakpro/attacks/attack_scheduler.py
  leakpro/attacks/minv_attacks/abstract_minv.py
  leakpro/attacks/minv_attacks/attack_factory_minv.py
  leakpro/attacks/minv_attacks/plgmi.py
  leakpro/attacks/utils/gan_handler.py
  leakpro/attacks/utils/gan_losses.py
  leakpro/attacks/utils/generator_handler.py
  leakpro/input_handler/minv_handler.py
  leakpro/input_handler/modality_extensions/image_metrics.py
  leakpro/leakpro.py
  leakpro/metrics/attack_result.py
  leakpro/schemas.py
  pyproject.toml
Labels: enhancement

#277 Fixing HSJ and DPSGD
  examples/mia/LOS/mimic_GRUD_dpsgd.ipynb
  examples/mia/cifar/audit.yaml
  leakpro/attacks/mia_attacks/HSJ.py
  leakpro/signals/utils/HopSkipJumpDistance.py
Labels: bug

#274 Fix for modality extension
  leakpro/leakpro.py
Labels: bug

#276 Fix tpr@0.0%fpr to not be N/A
  leakpro/metrics/attack_result.py
  leakpro/tests/test_attack_result/test_attack_result.py
Labels: bug

#269 Shadow Models vs Target Models
  examples/mia/LOS/utils/model_GRUD.py
  examples/mia/LOS/utils/model_GRUD_dpsgd.py
  examples/mia/LOS/utils/model_LR.py
  examples/mia/celebA_HQ/utils/celeb_hq_model.py
  examples/mia/cifar/audit.yaml
  examples/mia/cifar/cifar_handler.py
  examples/mia/cifar/cifar_main.ipynb
  examples/mia/cifar/target_model_class.py
  examples/mia/cifar/train_config.yaml
  examples/mia/cifar/utils/cifar_data_preparation.py
  examples/mia/cifar/utils/cifar_model_preparation.py
  examples/mia/tabular_mia/utils/adult_model_preparation.py
  leakpro/attacks/mia_attacks/lira.py
  leakpro/attacks/utils/boosting.py
  leakpro/attacks/utils/distillation_model_handler.py
  leakpro/attacks/utils/model_handler.py
  leakpro/attacks/utils/shadow_model_handler.py
  leakpro/input_handler/abstract_input_handler.py
  leakpro/input_handler/mia_handler.py
  leakpro/leakpro.py
  leakpro/metrics/attack_result.py
  leakpro/schemas.py
  leakpro/signals/signal.py
  leakpro/tests/constants.py
  leakpro/tests/input_handler/image_input_handler.py
  leakpro/tests/input_handler/image_utils.py
  leakpro/tests/input_handler/tabular_input_handler.py
  leakpro/tests/input_handler/tabular_utils.py
  leakpro/tests/input_handler/test_image_handler.py
  leakpro/tests/input_handler/test_tabular_handler.py
  leakpro/tests/mia_attacks/utils/test_model_handler.py
  leakpro/tests/mia_attacks/utils/test_shadow_model_handler.py
  leakpro/tests/test_attack_result/test_attack_result.py
  leakpro/utils/conversion.py
Labels: bug, enhancement
